apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: devfile-sample-hfiw
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: devfile-sample-hfiw
    app.kubernetes.io/part-of: ci1t-43256-0080-app
  name: devfile-sample-hfiw
spec:
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: nodejs-app
      app.kubernetes.io/instance: devfile-sample-hfiw
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: nodejs-app
        app.kubernetes.io/instance: devfile-sample-hfiw
    spec:
      containers:
      - image: quay.io/stonesoup_perfscale/ci1t-43256-0080-tenant/ci1t-43256-0080-app/devfile-sample-hfiw@sha256:97faa4f5c97db7306132f819974e732037e6ec77abe8743446ebc21a7d31e8bd
        name: my-nodejs
        ports:
        - containerPort: 3001
          name: http
          protocol: TCP
        resources:
          requests:
            cpu: 10m
            memory: 50Mi
status: {}
